name: CodeGuru Review

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - feature/**

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      actions: read
      contents: read
      security-events: write
      statuses: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0 # This is a required field for CodeGuru
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Print value of pull_request.files
      if: github.event_name == 'pull_request'
      run: 
        echo "This is a pull request event"
        echo "pull_request.files - ${{ github.event.pull_request.files }}"



    # - name: CodeGuru Reviewer
    #   uses: aws-actions/codeguru-reviewer@v1.1
    #   with:
    #     # source_commit: 
    #     s3_bucket: codeguru-reviewer-results-bucket-do-not-delete
    
    # - name: Print value of pull_request.files
    #   run: echo "pull_request.files are - ${{ github.event.pull_request.files }}"

    # - name: Filter results
    #   run: |
    #     CHANGED_FILES=$(jq '.pull_request.files[] | select(.status == "modified").filename' < ${{ github.event_path }})
    #     jq "select(.tool.name == \"AWS CodeGuru Reviewer\") | .results[] | select(.location.physicalLocation.artifactLocation.uri | test($CHANGED_FILES))" codeguru-results.sarif.json > filtered-results.sarif.json
    #   env:
    #     GITHUB_EVENT_NAME: ${{ env.GITHUB_EVENT_NAME }}
    #     GITHUB_EVENT_PATH: ${{ env.GITHUB_EVENT_PATH }}

    # - name: Upload review result
    #   if: ${{ github.event_name != 'push' }}
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     sarif_file: filtered-results.sarif.json # Results file will be named codeguru-results.sarif.json
