name: CodeScan Config

on:
  push:
    branches:
      - main
      - codescan

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/my-github-actions-role-test
        aws-region: us-west-2
